Update microbenchmarks readme
dotnet/performance pull request #1728
Opened 2021-03-16 05:06 UTC by danmoseley

Update to be net6.0 by default.
Move into docs (I missed it in the last pass because it's the only markdown not in docs)

2021-03-16 12:35 UTC, adamsitnik requested changes
@danmoseley thank you for keeping our docs up to date!

> Most people will come to this repo to run microbenchmarks.

If they come to this repo to run microbenchmarks, they already have the link to the right doc at the top of the docs list. If they go directly to the `src/benchmarks/micro`, the `README.me` is nicely printed:

![obraz](https://user-images.githubusercontent.com/6011991/111309271-fe358b80-865b-11eb-8d6d-35943a83aa75.png)

With your change we lose the latter:

![obraz](https://user-images.githubusercontent.com/6011991/111309322-0ee60180-865c-11eb-9bf6-48ec24a7ad67.png)

To be honest with you I don't like it and I would prefer to keep the old setting.

2021-03-16 12:35 UTC, adamsitnik commented on docs/microbenchmarks_workflow.md
> +If you contribute to [dotnet/runtime](https://github.com/dotnet/runtime) and want to benchmark **local builds of .NET Core** you need to build [dotnet/runtime](https://github.com/dotnet/runtime) in R
Should it be clr+lib**s** ?

```suggestion
If you contribute to [dotnet/runtime](https://github.com/dotnet/runtime) and want to benchmark **local builds of .NET Core** you need to build [dotnet/runtime](https://github.com/dotnet/runtime) in Release (including tests - so a command similar to `build clr+libs+libs.tests -rc release -lc release`) and then provide the path(s) to CoreRun(s). Provided CoreRun(s) will be used to execute every benchmark in a dedicated process:
```

2021-03-17 04:33 UTC, danmoseley commented
You are right. I removed the move. How does it look now?

2021-03-17 15:28 UTC, adamsitnik approved these changes
LGTM, thank you @danmoseley !

2021-03-17 15:28 UTC, merged