Disable ResultTable for Scenario Testing
dotnet/performance pull request #1924
Opened 2021-08-16 20:36 UTC by Tohron

This change skips generation of the result table if the current issues with the 3.1 runtime lead to necessary events not occurring.

2021-08-16 20:42 UTC, DrewScoggins commented
I think that a better approach here would be to disable the execution of the underlying scenarios in the yml file, rather than trying do this on the reporting side.

2021-08-16 21:26 UTC, DrewScoggins requested changes
See my other comment

2021-08-17 23:29 UTC, billwert requested changes

2021-08-17 23:29 UTC, billwert commented on src/tools/Reporting/Reporting/Reporter.cs
> +                foreach (var counter in topCounters)
Please undo all these changes as they are white-space only.

2021-08-17 23:29 UTC, billwert commented on eng/performance/scenarios.proj
> -
I would comment this out instead of delete it, as we will want to turn it back on at some point.

2021-08-17 23:41 UTC, billwert approved these changes

2021-08-18 17:45 UTC, DrewScoggins approved these changes
LGTM

2021-08-18 17:52 UTC, merged