Add processor affinity options scenarios
dotnet/performance pull request #3042
Opened 2023-05-24 18:05 UTC by LoopedBard3

2023-05-25 19:57 UTC, LoopedBard3 commented
Test run demonstrating the E2E working: https://dev.azure.com/dnceng-public/public/_build/results?buildId=285453&view=logs&jobId=85302f16-2cc4-5077-bbf0-683d7d61c604&j=85302f16-2cc4-5077-bbf0-683d7d61c604&t=b12d3e62-1722-50df-a17e-c06a6f3518be

2023-05-25 20:21 UTC, LoopedBard3 commented
Tested the affinity parameter in the E2E demonstration, but not keeping the test in. Instead will add the new scenario setup in its own PR, especially since there will be more than just affinity changed.

2023-05-25 22:04 UTC, kunalspathak commented on src/tools/ScenarioMeasurement/Util/ProcessHelper.cs
> +                    if (GuiApp)
As I mentioned offline, a better way to measure the startup is to ready the console output from PDN and remove the code that we have today for `AppStarted`, `AppIdle`, etc.

2023-05-26 06:39 UTC, cincuranet requested changes

2023-05-26 06:39 UTC, cincuranet commented on src/tools/ScenarioMeasurement/Startup/Startup.cs
> +        {
Use variable for `Process.GetCurrentProcess()` and reuse it, instead of doing the call again.

2023-05-26 20:34 UTC, LoopedBard3 commented on src/scenarios/shared/runner.py
> +        if self.testtype in [const.STARTUP, const.INNERLOOP, const.INNERLOOPMSBUILD, const.DOTNETWATCH, const.SDK, const.CROSSGEN, const.CROSSGEN2] and (args.affinity or os.environ.get('PERFLAB_DATA_
Would it be better to use getattr to check if affinity exists instead?

2023-05-30 17:43 UTC, LoopedBard3 commented on src/scenarios/shared/runner.py
> +        if self.testtype in [const.STARTUP, const.INNERLOOP, const.INNERLOOPMSBUILD, const.DOTNETWATCH, const.SDK, const.CROSSGEN, const.CROSSGEN2] and (args.affinity or os.environ.get('PERFLAB_DATA_
Attempted to make a good solution using getattr and couldn't come up with one that worked with both affinity passing options.

2023-05-30 19:06 UTC, cincuranet approved these changes

2023-05-30 19:39 UTC, merged