Normalize the dictionary order and values for Reporter Run Configs
dotnet/performance pull request #3360
Opened 2023-09-20 22:30 UTC by LoopedBard3

Normalize the dictionary order and values in the run configurations for the Reporter.cs generation. Also fixed some spacing.

2023-09-20 23:00 UTC, DrewScoggins commented on src/tools/Reporting/Reporting/Reporter.cs
> +                run.Configurations.Add(split[0], split[1].ToLower());
I am not exactly sure of what the impact of this would be. I think this should get split out into another PR so we have more time to think about it.

2023-09-20 23:14 UTC, DrewScoggins approved these changes
LGTM

2023-09-20 23:23 UTC, caaavik-msft commented
Before we merge this in, I think it may be worth evaluating if we can remove any dependency we have on the sort order of the configuration keys here. If the only issue in ADX reporting, I think it might be better to fix it in ADX's end by maybe adding a new column which concatenates all the config keys together in sorted order. This change would cause configurations that were almost always unsorted to suddenly become unsorted and will make the measurement history even more difficult to unify inside ADX.

2023-09-21 11:38 UTC, cincuranet commented
For my own understanding, what's actually the reason to have it ordered? Is there some problem this is solving? Otherwise LGTM.

2023-09-21 11:38 UTC, cincuranet approved these changes

2023-09-21 11:40 UTC, caaavik-msft requested changes
I'd like to block this PR until we've discussed this more since I think merging this will likely make things even more difficult when comparing runs from before this PR is merged in.

2023-09-27 16:39 UTC, DrewScoggins commented
One thing we should do here is get an answer on how many runs this will cause a break in, and when those runs have been happening. If only a small number of datapoints are going to be affected, I think that taking this change and just updating the old points should be worth it.

2023-09-27 19:23 UTC, LoopedBard3 commented
> One thing we should do here is get an answer on how many runs this will cause a break in, and when those runs have been happening. If only a small number of datapoints are going to be affected, I think that taking this change and just updating the old points should be worth it.

That makes sense, I will work on getting this information.

2023-10-03 20:24 UTC, LoopedBard3 commented
> > One thing we should do here is get an answer on how many runs this will cause a break in, and when those runs have been happening. If only a small number of datapoints are going to be affected, I think that taking this change and just updating the old points should be worth it.
> 
> That makes sense, I will work on getting this information.

After some testing to get the information on the Run Configs that would be affected by this change or similar ones, over half of the run configs returned would be in a different order. This does not group already differently ordered runconfigs, such as the ones seen with the ios_scenarios. Instead, I switched to using the individual columns for each Run Config option for what I needed. While this may be worth revisiting, I am going to close for now as I don't need this change for the work I am doing.

2023-10-03 20:24 UTC, closed without merging